# network architecture
# # encoder related
encoder: conformer
encoder_conf:
    output_size: 512    # dimension of attention
    attention_heads: 8
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: true
    cnn_module_kernel: 15
    use_cnn_module: True
    cnn_module_norm: 'layer_norm'
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'
    selfattention_layer_type: 'rel_selfattn'


# hybrid CTC/attention
model_conf:
    length_normalized_loss: false
    neg_weight: 0.0
    audio_mask_weight: 0.3
    text_mask_weight: 0.3


llm: qwen
llm_lora:
    lora_keys: ['all']
    r: 32
    alpha: 16
    dropout: 0.05
    use_adalora: false
    target_r: 4


dataset_conf:
    filter_conf:
        max_length: 1600
        min_length: 100
        token_max_length: 200
        token_min_length: 1
        max_output_input_ratio: 0.125
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    volume_perturb: false
    pitch_shift: false
    split_with_space: true
    token_mask: false
    token_mask_conf:
        p: 0.2
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 0.1
    spec_aug: false
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 10240
    sort: true
    sort_conf:
        sort_size: 512  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'static' # static or dynamic
        batch_size: 12
        max_frames_in_batch: 3000

grad_clip: 5
accum_grad: 1
max_epoch: 30
log_interval: 100

halflr:
    start_epoch: 20
    num_epoch: 30
    rate: 0.7

optim: adamw
optim_conf:
    lr: 0.0003
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 10000
